ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
EXECUTE IMMEDIATE 'CREATE USER mottrackeruser IDENTIFIED BY mottrackerpass';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01920 THEN NULL; 
ELSE RAISE;
END IF;
END;
/

GRANT CONNECT, RESOURCE TO mottracker;
GRANT UNLIMITED TABLESPACE TO mottracker;